### ISSUE TITLE
Invalid shape ID when parsing with baseIRI

### ISSUE THREAD

**Issue by rubensworks** [shexjs/shex.js#93]
When parsing the shape at http://shapes.pub/ns/medical-record/shex#MedicalRecordShape with the following code:
```js
const parser = shexParser.construct('http://shapes.pub/ns/medical-record/shex#MedicalRecordShape');
const schema = parser.parse(data);
```

the first shape has the id `"https://shapes.pub/ns/medical-record/MedicalRecordShape"`, while it is expected to be `"https://shapes.pub/ns/medical-record/shex#MedicalRecordShape"`.

I guess something may be going wrong with relative IRI to base resolution when fragments are present.

**Comment by ericprud** [comment]
Odd as it is, BASE URLs aren't allowed to have '#'s in them. c.f.
``` js
node -e 'console.log((new (require("n3")).Parser()).parse("BASE <https://shapes.pub/ns/medical-record/shex#> <MedicalRecordShape> a 1."));'
[
  Quad {
    id: '',
    _subject: NamedNode {
      id: 'https://shapes.pub/ns/medical-record/MedicalRecordShape'
    },
    _predicate: NamedNode { id: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
    _object: Literal { id: '"1"^^http://www.w3.org/2001/XMLSchema#integer' },
    _graph: DefaultGraph { id: '' }
  }
]
```

**Comment by ericprud** [comment]
> Ah indeed, you're right. I even [implemented this myself](https://github.com/rubensworks/relative-to-absolute-iri.js/blob/master/lib/Resolve.ts#L13-L16) at some point, but forgot about it facepalm

When I saw the issue, I dove into the parser with a hearty "WTF?" and only after some screwing around realized that the code looked very intentional about that behavior. Only then did I remember this behavior. I have apparently programmed myself to write Turtle nodes and ShEx shape (expr) labels with `<#...>` so I can cut down on how often I have to remember this arcane consequence of HTTP request mechanics.

> Then I guess the file at http://shapes.pub/ns/medical-record/shex just incorrectly describes `http://shapes.pub/ns/medical-record/shex#MedicalRecordShape`, right? Did you publish that file @ericprud? Or should I ask someone else about it?

Given the property names, it looks like an aggregator for a subset of the FHIR Resrouces (e.g. [Observation](http://build.fhir.org/observation.html#resource), etc.). Maybe someone at Janeiro (@justinwb?) wrote something like this and @jaxoncreed scooped it up? Maybe @jaxoncreed created it from whole cloth?
